apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCGsdkzaz+a67T0DQhXiMpBcYn20KG5pI/Sg5NHVtujXtXNhDq5EF46nA0ycoTc0akxSqFiMgP7/QRPkdsOjYdDwK1LZKgUYodyak1jit3SM/yN1SpS1GodIUERDA6pLugzqUVNrbnkcRnBj8i2n5QjKtEyHO73z0tG8XmIFVAl8+HW3+zZafGL6Yrl7q9QRCHLXq7tjTCH4DW0jjvIrG8TZPuKGLtiR2YP+TnAdKg4W8944EnpZTORc46iE0p5+4/z/TAtQjYnzio2zg54AjgzxskdAJlLDCyWAYQTBZ7bgX72RMsD6VpN34HHNdcOVRWyn3FzbVRaX4ciPsqUEgGWSR3p/AQkr8onRqk9U8922mtNMHdb5+kU3yUbN39X48u4s1io+KEnoQbKQ5LzL3pk11WFNEO/ZnvDySpsq0dYMB+uiYtOlTi5hN++KEVbwPM5bF0192zh6Udj44aehq778FxQ66Jxiu6II1XSGyLivWUpl0R6LykrbiFWCS7a1DDvCBeXcpvHIdUxXioKax3vcheleDAt6A9UAEwyJNypt5r0IcB2vIA3aEvpngxiITPJikUrZKiZ1PJGYUweIUO6eaR5baz7vG5Z1UjxQNYSUI8z6pIk/oB/kzpjDbt1yb5YcACAy9w+R7Ror4fiPE2CDDBs0AX+RNpMjKX5ej6KSfcd4UnFuI/VMZgnHYXl6taWGnQuzBntcGoai61dRr/R+2p2+w==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
