apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCqkgAnzzQrJck9uPnhjoC/Sxr0oNsz+96C1V/AkeeFdM3v+I9sTm0wGuBd3vQvw+b3TNHes0AjrGgqAifyozCvllkr5eVie8mxCgABdjJXmMWV+uPqDsHBujFMvcmqau3P26FXaifd/c/ALmd4kUeU86j7J49MFNDNr/Z/XE99RtAUZc9caJf9zIMdj07rkwbYAhzzgFDKqY7OgkanyERqnoudaNGNh54uFVDa4yv3nwmqniiDu9M7osntblseDLMIaMpw6wzA3qH1fE/t5QylfhhHDXNa4pht+vV+kFQZr9TjXi2us0Dq/zJ/V03Kvm/0f/Aes5y7WQgWTWR+WOcHbB/FtubymQhfbcI/X8zkCGuvSGxB1Ce1MpCsdlOdnInVsaweKLrcoMC0XKgVWycNjLb6ZfeP/SiaODw4Wscxb1WSNRJg8JOadRT2NBWLFYPfMmna6gzqF4JD1pKHTuLTYInTCoVzktafWzuYU/9DjLqDqHDST6mX7bOQynWjaqE9VkyTJ4YColRJvGTCwEYi8im3lKL9ccigcvsOYhcuixOiYOPP1LEVEqnrGnZMHsdkekvY0tqsJEFnbCucLbmHTv87leGQ8N8EPgKptv7xbDZHe26OwgDsyx71HlPtSjZov9fxeyHCU8xDmxZEG+7vcAG3swzkLkRvCIt2D4RccTUU+xuxIepCrnWxefl8OAbs+o4xfYEi0+wQsE3c0aErrDqGHQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
